name: PR Views to kozmoai/nebula

on:
#  push:
#    branches:
#      - main
#    paths:
#      - "views/aggregate-worker-metadata.json"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.OSS_PRS_RW }}

jobs:
  update-views:
    name: Send updated views to kozmoai/nebula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Open PRs to kozmoai/nebula
        run: |
          NEW_BRANCH="update-worker-metadata-$(date +%Y%m%d%H%M%S)"
          TARGET_FILE_PATH="src/nebula/server/api/collections_data/views/aggregate-worker-metadata.json"
          SOURCE_REPO_URL="https://raw.githubusercontent.com/kozmoai/nebula-collection-registry/main/views/aggregate-worker-metadata.json"

          git clone https://github.com/kozmoai/nebula.git
          cd nebula

          curl -o $TARGET_FILE_PATH $SOURCE_REPO_URL

          git checkout -b $NEW_BRANCH
          git add $TARGET_FILE_PATH
          git commit -m "Update aggregate-worker-metadata.json"
          git push --set-upstream origin $NEW_BRANCH

          gh pr create --repo kozmoai/nebula --base main --head $NEW_BRANCH --title "Automated PR for Worker Metadata Update" --body "This is an automated PR to update the worker metadata."
